development:
  api_key: 178219802255919
  secret_key: f1b13483eaf44cf495fe3781181a23f8
  canvas_page_name: csextended
  callback_url: http://127.0.0.1:1234/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 244991168891714
  secret_key: 3d246bb849d1f50eece7292b2e39d700
  canvas_page_name: csextended
  callback_url: http://cs.karissayu.com/
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

